dataset:
  root: "./data"
  keep_classes:
    - "Esophagus"      # cls idx 7
    - "Cervix"         # cls idx 13
    - "Adrenal_gland"  # cls idx 14
    - "Bile-duct"      # cls idx 15

retriever:
  img_sz: 224
  model_arch: "google/vit-base-patch16-224-in21k"
  wt_ckpt: "model-ckpts/best_vit_model.pt" # Load a set of weights that is not pretrained
  use_grayscale: False
  embedding_dir: "embed_database.pt"
  num_db_images_per_class: 20

generator:
  img_sz: 128
  batch_sz: 8
  in_ch: 1
  out_ch: 1

train_args:
  epochs: 50
  lr: 1e-3
  weight_decay: 0.1
  diffusion_steps: 1000
  save_ckpt_name: "./test-rag.pt"
  log: "./test_logs_rag"