dataset:
  root: "/home/lnair/image-diffusion/clean-diffusion-code/data"
  keep_classes:  # Classes from the dataset to use for training and evaluation
    #- 'Breast'
    #- 'Colon'
    #- 'Lung'
    #- 'Kidney'
    #- 'Prostate'
    #- 'Bladder'
    #- 'Stomach'
    - 'Esophagus'
    #- 'Pancreatic'
    #- 'Uterus'
    #- 'Thyroid'
    #- 'Ovarian'
    #- 'Skin'
    - 'Cervix'
    - 'Adrenal_gland'
    - 'Bile-duct'
    #- 'Testis'
    #- 'HeadNeck'
    #- 'Liver'

retriever:
  img_sz: 224
  batch_sz: 8
  model_arch: "google/vit-base-patch16-224-in21k"
  wt_ckpt: "best_vit_model.pt"
  use_grayscale: False
  embedding_dir: "embeddings.pt"  # Save the compiled database of retrieval image embeddings
  num_db_images_per_class: 20

generator:
  img_sz: 128
  batch_sz: 8
  in_ch: 1
  out_ch: 1

train_args:
  epochs: 20
  lr: 1e-3
  diffusion_steps: 1000
  save_ckpt_name: "test_rag_with_retrieval.pt"
  log: "./test_logs_rag"