generator:
  img_sz: 64
  batch_sz: 4
  in_ch: 1
  out_ch: 1

expert:
  img_sz: 224
  batch_sz: 64
  in_ch: 1
  save_ckpt_name: "r50_grayscale.pt"
  dataset_folder: "Kather_texture_2016_image_tiles_5000"
  epochs: 15
  lr: 0.0001
  gamma: 0.7
  

train_args:
  epochs: 20
  lr: 1e-4
  diffusion_steps: 1000
  save_ckpt_name: "pretrained-diff.pt"
  log: "./pretrained-diff-logs"